application:
  version: v1.0.0
  title: cntech-food-list
spring:
  thymeleaf:
    cache: false
    mode: HTML
  devtools:
    livereload:
      enabled: true
      port: 35729
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cntech_qr?useUnicode=true&charaterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: tkddnjs0823
  jap:
    hibernate.ddl.auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: Asia/Seoul
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect